version: 2
jobs:
  node8:
    docker:
      - image: circleci/node:carbon

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys: 
            - v1-dependencies-cache-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn run setup

      - save_cache:
          key: v1-dependencies-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: test
          command: yarn test

      - run:
          name: coverage
          command: yarn run coverage
  
  node6:
    docker:
      - image: circleci/node:boron

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys: 
            - v1-dependencies-cache-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn run setup

      - save_cache:
          key: v1-dependencies-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: test
          command: yarn test

      - run:
          name: coverage
          command: yarn run coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - node10
      - node9
      - node8
      - node6