version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys: 
            - v1-dependencies-cache-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn run setup

      - save_cache:
          key: v1-dependencies-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: test
          command: yarn test

      - run:
          name: coverage
          command: yarn run coverage

  node10:
    <<: *node-base
    docker:
      - image: node:10

  node9:
    <<: *node-base
    docker:
      - image: node:9
      
  node8:
    <<: *node-base
    docker:
      - image: node:8
  
  node6:
    <<: *node-base
    docker:
      - image: node:6

workflows:
  version: 2
  build_and_test:
    jobs:
      - node10
      - node9
      - node8
      - node6